-- 1. Création de la table products
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR(150) NOT NULL,
  categorie VARCHAR(50) NOT NULL,
  prix VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  materiaux VARCHAR(150) DEFAULT NULL,
  dimensions VARCHAR(150) DEFAULT NULL,
  image VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Insertion de test
INSERT INTO products (nom, categorie, prix, description, materiaux, dimensions, image) VALUES
('Cuisine Émeraude', 'Cuisine', '450 000 FCFA', 'Finition laquée haute qualité.', 'MDF Laqué & Quartz', 'Sur-mesure', 'cuisine1.jpg');

-- 3. Autorisation d'accès public en lecture (obligatoire pour Supabase)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Lecture publique des produits"
ON products FOR SELECT
TO anon, authenticated
USING (true);